version: '3.8'

services:
  app:
    build: .
    container_name: java_app
    depends_on:
      - minio
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioaccesskey
      MINIO_SECRET_KEY: miniosecretkey
    ports:
      - "8080:8080"

  minio:
    image: minio/minio:RELEASE.2022-03-19T06-45-50Z
    container_name: minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minioaccesskey
      MINIO_ROOT_PASSWORD: miniosecretkey
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
